name: React Frontend CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Run React build
        run: |
          cd frontend
          npm run build

      - name: Run tests 
        run: |
          cd frontend
          npm test || echo "No tests yet"
